### ISSUE TITLE
Wrong repo link on deno.land

### ISSUE THREAD

**Issue by chmac** [BlowaterNostr/nostr.ts#103]
Firstly, thanks for bringing nostr to deno!

I noticed that the https://deno.land/x/nostrts@3.0.2 page links to the wrong repo, it points to your csp repo instead of this one.

**Comment by bob2402** [comment]
Thank you for your feedback.

I reviewed [deno.land/x/nostrts@3.0.2](https://deno.land/x/nostrts@3.0.2) and confirmed that the link is correct. The CSP link on the left is listed under dependencies, and the subtitle `github.com` may have caused some confusion.

Additionally, we have released this library at https://jsr.io/@blowater/nostr-sdk, which features a newer version. You are welcome to use it.

If you have any questions in the future, please feel free to reach out.

**Comment by chmac** [comment]
You're totally right, I missed the repo link and saw the dependency link instead.

Will close this issue now.

**Comment by BlowaterNostr** [comment]
@chmac thanks for checking out this work. I appreciate your feedback.
@bob2402 Thanks for responding.
