### ISSUE TITLE
Breaking Change Request: redesign updateSub's API

### ISSUE THREAD

**Issue by BlowaterNostr** [BlowaterNostr/nostr.ts#16]
# Problem
Consider
```ts
const subID = "xxx"
const stream1 = await pool.newSub(subID, {...});
const stream2 = await pool.updateSub(subID, {...});
```
Currently, `stream1` and `stream2` are the same reference. Updating a subscription won't kill the channel created by the previous subscription.

This is an abstraction invented by `nostr.ts` since nostr protocol does not have the concept of updating an existing subscription. Our implementation close the previous subscription and creates a new subscription with the same name.

This design looks nice and convenient at first, but after several months' practice, I find this API behavior might not be desireable.

1. Hard to debug
In Blowater's production, we encountered dangling promises or starvation of channels. https://github.com/BlowaterNostr/blowater/issues/115
The root cause is still unknown but this API design should be related because Blowater did not have this problem before introducing `updateSub`

2. Dangling Async Functions
Consider https://github.com/BlowaterNostr/blowater/blob/main/features/profile.ts#L23-L38
If `add` is called multiple times, many `resp.chan` will be created. Logically it's still correct because they all add to the same database instance. But we will create unncessary amount of promises that never resolves. This is result in memory leak over time.

3. Unclear responsibility for channel consumers
In a real world situation, `stream1` and `stream2` are likely to be constructed in different places of the code and in different time. Since `stream1` and `stream2` are the same reference. Their consumers effectly are racing to read from the same channel which might not be desired and might cause surprising data loss from individual consumer's perspective.

4. Suprising Data for consumers
Following No.2, the reader of `stream1` might be surprised that it gets data which doesn't match its original filter.

# Proposal
1. Must
We should close the channel of `stream1` when `updateSub` is called, making `stream1` and `stream2` 2 separate references. 

2. Maybe
Forbid the reuse of the same subscription id for different subscriptions and remove `updateSub`.

In this case, the caller of this API should do
```js
const stream1 = await pool.newSub("profileStream 1", {...});
const stream2 = await pool.updateSub("profileStream 2", {...});
```
Use a suffix index to indicate that it's from the same feature but for different iterations.

**Comment by GuandeLi2** [comment]
I think both proposals should be done.But we can do it step by step.We can do the first proposal first, and then do the second.

**Comment by BlowaterNostr** [comment]
@GuandeLi2 Why do you think No.2 is necessary?

**Comment by BlowaterNostr** [comment]
- After many months of experiment, I decide to remove `updateSub` for all the complexity it introduces. #35
