### ISSUE TITLE
Allow to specify relay list in sub and sendEvent methods

### ISSUE THREAD

**Issue by verbiricha** [BlowaterNostr/nostr.ts#3]
Would be nice to be able to specify a relay list on methods that interact with nostr for sub and pub. If a connection is not already open to any of the relays an ephemeral connection can be open for the duration of the sub.

**Comment by BlowaterNostr** [comment]
@verbiricha Sorry for the late response, what do you mean by `If a connection is not already open to any of the relays an ephemeral connection can be open for the duration of the sub.`?

`specify a relay list on methods that interact with nostr for sub and pub`
If the `ConnectionPool` is constructed with relay `A, B, C`, do you want the `newSub` and `sendEvent` to accept a subset of `A,B,C` or extra relays?

`sendEvent` and `newSub` will work asynchronously once connections are open. I don't see the need of `an ephemeral connection can be open for the duration of the sub`

**Comment by BlowaterNostr** [comment]
https://app.coracle.social/note14qpd06k5vd6pyf3wxrvpnmgky2kdj4yy0an5r2yh74n6uvkpau9sj5q2fl

**Comment by BlowaterNostr** [comment]
@verbiricha close since no response and I believe the original request was mistaken.
